set PATH=%PATH%;C:\Program Files\apache-maven-3.5.0\bin

call mvn install:install-file -DgroupId=com.snobot.simulator -Dversion=1.0 -DlocalRepositoryPath=C:\Users\PJ\GitHub\FIRST_2017\maven_repo -Dpackaging=jar -DartifactId=snobotSim                                 -Dfile=C:\Users\PJ\GitHub\FIRST_2017\WpiUpdates\WpiHalRefactor\build\snobotSim.jar
call mvn install:install-file -DgroupId=com.snobot.simulator -Dversion=1.0 -DlocalRepositoryPath=C:\Users\PJ\GitHub\FIRST_2017\maven_repo -Dpackaging=jar -DartifactId=snobotSim -Dclassifier=gui                -Dfile=C:\Users\PJ\GitHub\FIRST_2017\WpiUpdates\WpiHalRefactor\build\snobotSimGui.jar
call mvn install:install-file -DgroupId=com.snobot.simulator -Dversion=1.0 -DlocalRepositoryPath=C:\Users\PJ\GitHub\FIRST_2017\maven_repo -Dpackaging=jar -DartifactId=snobotSim -Dclassifier=NativeJava-windows -Dfile=C:\Users\PJ\GitHub\FIRST_2017\WpiUpdates\WpiHalRefactor\build\snobotSimNative-windows.jar
call mvn install:install-file -DgroupId=com.snobot.simulator -Dversion=1.0 -DlocalRepositoryPath=C:\Users\PJ\GitHub\FIRST_2017\maven_repo -Dpackaging=zip -DartifactId=snobotSim -Dclassifier=cpp-sources        -Dfile=C:\Users\PJ\GitHub\FIRST_2017\WpiUpdates\WpiHalRefactor\build\snobotSimCppSources.zip
call mvn install:install-file -DgroupId=com.snobot.simulator -Dversion=1.0 -DlocalRepositoryPath=C:\Users\PJ\GitHub\FIRST_2017\maven_repo -Dpackaging=zip -DartifactId=snobotSim -Dclassifier=javadeps           -Dfile=C:\Users\PJ\GitHub\FIRST_2017\WpiUpdates\WpiHalRefactor\build\snobotSimJavaDependencies.zip
call mvn install:install-file -DgroupId=com.snobot.simulator -Dversion=1.0 -DlocalRepositoryPath=C:\Users\PJ\GitHub\FIRST_2017\maven_repo -Dpackaging=zip -DartifactId=snobotSim -Dclassifier=NativeCpp-windows  -Dfile=C:\Users\PJ\GitHub\FIRST_2017\WpiUpdates\WpiHalRefactor\build\snobotSimLibrary-windows.zip

call mvn install:install-file -DgroupId=edu.wpilib -Dversion=1.0 -DlocalRepositoryPath=C:\Users\PJ\GitHub\FIRST_2017\maven_repo -Dpackaging=zip -DartifactId=wpilibSim                 -Dfile=C:\Users\PJ\GitHub\FIRST_2017\xxxTempWpi\wpilibSim.zip 
